# Generated by Django 5.1.3 on 2025-01-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
