# Generated by Django 5.1.3 on 2025-01-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_orderitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
