# Generated by Django 5.1.1 on 2025-05-02 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_wallet_transaction'),
        ('shop', '0008_delete_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'آیتم سفارش', 'verbose_name_plural': 'آیتم\u200cهای سفارش'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['-id'], 'verbose_name': 'آدرس حمل و نقل', 'verbose_name_plural': 'آدرس\u200cهای حمل و نقل'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-created_at'], 'verbose_name': 'کیف پول', 'verbose_name_plural': 'کیف پول\u200cها'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_successful',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'کیف پول'), ('gateway', 'درگاه پرداخت'), ('unknown', 'نامشخص')], default='unknown', max_length=10, verbose_name='روش پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('canceled', 'لغو شده')], default='pending', max_length=10, verbose_name='وضعیت سفارش'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payment.order', verbose_name='سفارش مرتبط'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.shippingaddress', verbose_name='آدرس حمل و نقل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='Shipping_address1',
            field=models.CharField(blank=True, max_length=100, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='Shipping_city',
            field=models.CharField(blank=True, max_length=25, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='Shipping_email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='Shipping_full_name',
            field=models.CharField(max_length=100, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='Shipping_phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='Shipping_postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='Shipping_province',
            field=models.CharField(blank=True, max_length=25, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='Shipping_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه پرداخت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت'), ('purchase', 'خرید'), ('refund', 'عودت')], max_length=10, verbose_name='نوع تراکنش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.wallet', verbose_name='کیف پول'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
