# Generated by Django 5.1.3 on 2025-01-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
