# Generated by Django 5.1.3 on 2025-01-26 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
