# Generated by Django 5.1.3 on 2024-11-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
